spring:

  application:
    name: shop_we
  datasource:
    url: jdbc:mysql://localhost:3306/shop_we?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB


server:
  port: 8080

weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "f3EBxGArPSLcuA/hMpozbP7r5qSMPfyto+DPhoG6O3pCeMhvbje4mmGdHyDBhg3nqSaESnS3Lf44giG5C1qekw=="


schedule:
  cron: 0 * 9 * * ?  # 매일 실행
  use: true           # 사용 여부

mybatis:
  mapper-locations: classpath:mapper/*.xml

