spring:
  application:
    name: shop_we
  datasource:
    url: jdbc:mysql://localhost:3306/shop_we?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

