spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_we?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  mapper-locations: classpath:mapper/*xml

server:
  port: 8080